version: '3'
services:
  php:
    hostname: wallet
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '9951:80'
