<?php

/* @var $this yii\web\View */

$this->title = Yii::$app->name;
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully connected to your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="https://txlab.it">Get started with txLab</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Payments and money transfer</h2>

                <p>Payments are made directly to the blockchain system with no intermediaries resulting in little or no transaction fees and faster transaction speed.

The payment and finance sector is without doubt the flagship sector in which the blockchain is mostly used. In 2009 Bitcoin was born to allow direct and “trustless” payment network systems with the absence of a centralized body. Since its development, a plethora of projects have been born leading to exponential development in this effective and efficient transaction system of payments and transfers.
                </p>

                <p><a class="btn btn-default" href="https://txlab.it/?page_id=773#">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Retail and fidelity programs</h2>

                <p>The blockchain is an efficient way to manage retail and fidelity programs. It tends indeed to make these systems cheaper and more secure. It reduces the number of intermediaries required for the cards emission and for the sales operations. The ability to participate in a gift card buy and sell process is made more efficient and convenient. Fraud attempts are less frequent because a blockchain approach requires a trusted automated user authentication.</p>

                <p><a class="btn btn-default" href="https://txlab.it/?page_id=773#">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Management and finance</h2>

                <p>Banks and the financial world are major investors in the blockchain because it is developed upon the process of a decentralized ledger, generated by a safe and unbreakable system resulting in lower administrative fees.

“DeFi” or Decentralized Finance is ready to explode thanks to projects that are taking the financial world into decentralized blockchains making this environment extremely attractive to potential participants in the system. Today it is possible to deposit an amount on lending platforms gaining interest or applying for loans paying reduced interest rates, all without having to trust intermediaries or centralized third parties.

The DeFi system is made possible because the amount of a given transaction is blocked inside smart contracts in the code which are “auditable” by everyone participating in the network.</p>

                <p><a class="btn btn-default" href="https://txlab.it/?page_id=773#">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>
